-- Local test harness only. Recreates the tables, roles and grants that db/00..20 assume already
-- exist in Supabase, so the migrations can be replayed against a throwaway Postgres container.
-- Never run this against a real database.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
end $$;

grant usage on schema public, extensions to anon, authenticated;

create table boards (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  password_hash text
);

create table columns (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references boards(id),
  name text not null,
  "position" integer not null default 0,
  created_at timestamptz not null default now()
);

create table cards (
  id uuid primary key default gen_random_uuid(),
  column_id uuid not null references columns(id),
  title text not null,
  description text,
  color text,
  due_date timestamptz,
  "position" integer not null default 0,
  created_at timestamptz not null default now()
);

create table card_history (
  id uuid primary key default gen_random_uuid(),
  card_id uuid references cards(id),
  from_column text,
  to_column text,
  "timestamp" timestamptz not null default now()
);

create table tags (
  id uuid primary key default gen_random_uuid(),
  board_id uuid not null references boards(id),
  name text not null,
  color text
);

create table card_tags (
  card_id uuid not null references cards(id),
  tag_id uuid not null references tags(id),
  primary key (card_id, tag_id)
);

create table global_stats (
  id integer primary key generated by default as identity,
  boards_created bigint not null default 0,
  cards_created bigint not null default 0,
  cards_moved bigint not null default 0,
  last_updated timestamptz not null default now()
);

-- Supabase hands the API roles blanket table access by default; the lockdown blocks in
-- db/04 and db/06 exist to take it away, so grant it here for those revokes to mean something.
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
